import { ContactBand, Label, PageIntro } from '@/components/site';
import { principles } from '@/lib/content';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('About', 'A small engineering company built around direct communication, experienced engineers and thoughtful decisions about software.', '/about/');
export default function About() { return <>
  <PageIntro label="About the company" title={<>Small enough to stay close.<br/><em>Experienced enough</em><br/>to take responsibility.</>}><p>A senior engineering boutique working on software products, existing systems and business integrations. The focus is useful, maintainable software and a direct relationship with the people who need it.</p></PageIntro>
  <section className="about-editorial section container"><Label number="01">The working model</Label><div className="editorial-copy"><h2>Keep the distance<br/>between problem and builder short.</h2><p>Software work needs judgement as much as implementation. Someone has to understand the business context, ask the difficult questions and take responsibility for the technical choices.</p><p>A small team keeps those responsibilities together. The engineers discussing the problem stay involved in building the solution. Decisions do not have to travel through layers of account management.</p><p>A limited number of simultaneous engagements protects the attention each project needs. Capacity and fit are discussed honestly before an engagement is agreed.</p></div></section>
  <section className="situations section"><div className="container section-heading"><Label number="02">Who this is for</Label><div><h2>Different teams.<br/>A shared need for dependable software.</h2><div className="audience-list"><article><h3>Startups</h3><p>A first production product with thoughtful foundations, a focused scope and room to develop.</p></article><article><h3>Small and mid-sized businesses</h3><p>Custom software for a real operational need, without requiring a large internal engineering organization.</p></article><article><h3>Existing product teams</h3><p>Experienced engineering capacity, architectural judgement or ownership of a difficult technical area.</p></article></div></div></div></section>
  <section className="section container"><div className="section-heading"><Label number="03">What guides the work</Label><div><h2>Practical choices.<br/>Long-term care.</h2></div></div><div className="principle-grid">{principles.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div><div className="ai-note"><Label>On AI</Label><p>AI is useful when it solves a specific problem. Where a workflow benefits from it, the work includes evaluating its limits, handling data appropriately and deciding where human review belongs. It is one tool in the engineering toolkit.</p></div></section>
  <section className="about-editorial section container border-top"><Label number="04">The client relationship</Label><div className="editorial-copy"><h2>Clear conversations.<br/>Visible progress.</h2><p>Expect direct contact with the people doing the work, discussions of trade-offs in plain language and regular reviews of working software.</p><p>Handover and ongoing support are part of the planning conversation. Code, documentation, access and operational responsibilities should be understood before a project reaches its final delivery.</p></div></section><ContactBand/>
</>; }
