import { LegalPage } from '@/components/legal';
import { company } from '@/lib/company';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Privacy policy', 'How information is handled when visiting this company website or contacting the company.', '/privacy/');
export default function Privacy() { return <LegalPage title="Privacy policy" intro="This notice describes information handling for this website and business enquiries. It does not replace a project-specific data processing agreement." sections={[
  { id:'operator', title:'Who is responsible', content:<><p>The website operator is {company.legalName}, registered in {company.jurisdiction}, at {company.address}.</p><p>Privacy contact: {company.email}.</p></> },
  { id:'information', title:'Information involved', content:<><p>The website itself has no enquiry submission form, user accounts or file uploads. If you contact the company by email, the information involved may include your name, email address, company and the content of your message.</p><p>The hosting provider may process technical request information, such as IP addresses, request times and browser details, to serve and secure the website. [CONFIRM HOSTING PROVIDER, DATA CATEGORIES AND LOGGING PRACTICES].</p></> },
  { id:'purpose', title:'Purposes and legal basis', content:<><p>Business enquiry information is used to understand and respond to your request, discuss potential work and manage relevant business correspondence.</p><p>[CONFIRM APPLICABLE PRIVACY LAW AND THE LEGAL BASIS FOR EACH PROCESSING PURPOSE]. No consent to marketing is assumed from a project enquiry.</p></> },
  { id:'cookies', title:'Cookies and analytics', content:<><p>This website implementation does not add analytics, advertising trackers or browser storage for marketing purposes.</p><p>A private preview may require hosting-platform access controls. [CONFIRM ANY HOST-ADDED COOKIES AND THEIR PURPOSES BEFORE PUBLIC LAUNCH]. If analytics or other tracking is introduced, this notice and any required consent controls must be updated first.</p></> },
  { id:'providers', title:'Service providers and transfers', content:<><p>Website hosting and business email providers may process information on behalf of the operator. [IDENTIFY PROVIDERS, PROCESSING LOCATIONS AND RELEVANT SAFEGUARDS].</p><p>[CONFIRM WHETHER INTERNATIONAL TRANSFERS OCCUR AND THE APPLICABLE TRANSFER MECHANISM].</p></> },
  { id:'retention', title:'Retention and security', content:<><p>Retention periods must reflect the purpose of the correspondence and any applicable recordkeeping requirements. [CONFIRM RETENTION PERIODS OR CRITERIA FOR ENQUIRIES, EMAIL AND HOSTING LOGS].</p><p>[CONFIRM THE OPERATOR’S ACTUAL SECURITY MEASURES]. Please do not include credentials or sensitive personal information in an initial enquiry.</p></> },
  { id:'rights', title:'Your rights and questions', content:<><p>You can contact {company.email} with a privacy question or a request concerning your personal information.</p><p>[CONFIRM APPLICABLE ACCESS, CORRECTION, DELETION, RESTRICTION, OBJECTION AND PORTABILITY RIGHTS, AS WELL AS COMPLAINT ROUTES AND SUPERVISORY AUTHORITY DETAILS].</p></> },
  { id:'changes', title:'Changes to this notice', content:<p>The effective date above identifies the current notice. Material changes to information handling should be reflected here before they take effect.</p> },
]} />; }
