import Link from 'next/link';
import { Label, ContactBand } from '@/components/site';
import { capabilities, principles, process } from '@/lib/content';
import { pageMetadata } from '@/lib/metadata';
export const metadata = pageMetadata('Software built for real use', 'SaaS products, web applications, software modernization, APIs and automation. Experienced engineers, direct collaboration and maintainable software.', '/');
export default function Home() { return <>
  <section className="hero container"><Label>Independent software engineering</Label><div className="hero-grid"><h1>Software built<br/>for <em>real use.</em></h1><div className="hero-copy"><p>Build a product. Improve a system.<br/>Connect the tools your business runs on.</p><p className="muted">A small engineering company for teams that need experienced people to turn complex problems into dependable software.</p><Link href="/contact/" className="button">Discuss a project</Link></div></div><div className="hero-baseline"><span>Small team. Direct collaboration.</span><span>From the first decision to production.</span><a href="#capabilities" className="scroll-link">Explore our capabilities <span aria-hidden="true">↓</span></a></div></section>
  <section id="capabilities" className="section container"><div className="section-heading"><Label number="01">Capabilities</Label><div><h2>Three ways to<br/>move your software forward.</h2><p>New software, existing systems, and the connections between them.</p></div></div><div className="capability-list">{capabilities.map(c => <Link href={`/capabilities/#${c.id}`} className="capability-row" key={c.id}><span className="row-number">{c.number}</span><h3>{c.title}</h3><p>{c.summary}</p><span className="row-action">Explore<span aria-hidden="true"> +</span></span></Link>)}</div></section>
  <section className="situations section"><div className="container"><div className="section-heading"><Label number="02">The work in practice</Label><div><h2>Real business needs.<br/>Useful software.</h2><p>The shape of the work starts with the problem, not a preferred technology.</p></div></div><div className="situations-grid"><div className="situations-intro"><p>For startups building their first serious product. Businesses improving how they operate. Product teams tackling a difficult technical area.</p><Link href="/capabilities/" className="text-link">Find the right starting point</Link></div><dl className="situations-list"><div><dt>A product ready to become real.</dt><dd>SaaS applications, customer portals and MVPs with a path beyond launch.</dd></div><div><dt>A system that is holding you back.</dt><dd>Inherited codebases, risky releases and architecture that has become difficult to change.</dd></div><div><dt>Too much work between your tools.</dt><dd>Internal tools, APIs and data workflows that reduce repeated manual work.</dd></div></dl></div></div></section>
  <section className="section container"><div className="section-heading"><Label number="03">Working together</Label><div><h2>Close to the problem.<br/>Accountable for the work.</h2><p>You speak directly with the engineers building your software.</p></div></div><div className="process-grid">{process.map(([title, text], i) => <article key={title}><span className="row-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="principles section container"><div className="section-heading"><Label number="04">Engineering judgement</Label><div><h2>Good decisions outlast<br/>the first release.</h2></div></div><div className="principle-grid">{principles.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="about-home section container"><Label number="05">Small by design</Label><div><h2>The people you talk to<br/>are the people who build.</h2><p>A limited number of engagements keeps attention on the work. Senior engineers stay involved in the decisions, the implementation and the conversations that connect them.</p><Link href="/about/" className="text-link">Get to know the company</Link></div></section>
  <ContactBand/>
</>; }
