export const capabilities = [
  { id: 'product-engineering', number: '01', title: 'Product engineering', summary: 'From a first useful release to a product your business can depend on.', description: 'Turn a defined business need into working software. Product decisions, architecture and implementation stay connected, so the first release has a clear purpose and a sensible path forward.', when: 'You need to launch a new product, replace a spreadsheet-driven process, or give customers a better way to work with your business.', work: ['SaaS products and web applications', 'Internal tools and operational software', 'Customer and partner portals', 'MVPs built for continued development'], outcome: 'A working product, a documented codebase and a clear plan for operating and improving it.' },
  { id: 'software-modernization', number: '02', title: 'Software modernization', summary: 'Make existing software easier to change, operate and build on.', description: 'Understand the system before deciding what to change. Preserve what works, address the areas creating risk, and improve the software in manageable steps. A rewrite is a decision to justify, not the default.', when: 'Releases feel risky, changes take too long, an inherited codebase needs ownership, or your product has outgrown its original architecture.', work: ['Codebase assessment and technical planning', 'Incremental refactoring and targeted rebuilds', 'New capabilities in existing products', 'Reliability, testing and maintainability improvements'], outcome: 'A more understandable system, reduced technical risk and a practical route to further development.' },
  { id: 'integrations-automation', number: '03', title: 'Integrations & automation', summary: 'Connect your systems. Give people back the work software can handle.', description: 'Build dependable connections between the tools your business already uses. Account for incomplete data, failed requests and the people who need to understand what happened when something goes wrong.', when: 'People re-enter the same data, systems do not exchange information, or a recurring operational task takes more attention than it should.', work: ['APIs and third-party integrations', 'Backend services and business workflows', 'Data synchronization and processing', 'AI-assisted workflows with appropriate human review'], outcome: 'Useful automation with clear failure handling, visible operations and ownership your team can understand.' },
] as const;
export const principles = [
  ['Keep the system understandable.', 'Use the simplest architecture that meets the real requirements. Complexity needs a reason.'],
  ['Choose technology in context.', 'Business constraints, existing systems and the people maintaining the software guide the stack.'],
  ['Treat production as part of the work.', 'Testing, security, accessibility, deployment and monitoring belong in the plan from the beginning.'],
  ['Make ownership clear.', 'Document the decisions, explain the trade-offs and leave software another engineer can work with.'],
] as const;
export const process = [
  ['Understand', 'Start with the business problem, the users and the constraints. Agree on what a useful result looks like.'],
  ['Build', 'Work in small increments. Review working software together and make trade-offs visible as the project develops.'],
  ['Ship & support', 'Prepare for real use, document the system and agree on handover or continued development.'],
] as const;
